In [1]:
import numpy as np
import pandas as pd

# Exercise 1
arr1 = np.arange(1, 11)
reshaped_arr = arr1.reshape(2, 5)
print("Exercise 1 - 2x5 Matrix:\n", reshaped_arr)


Exercise 1 - 2x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
# Exercise 2
arr2 = np.arange(1, 21)
extracted = arr2[5:16]
print("\nExercise 2 - Extracted elements (index 5 to 15):\n", extracted)



Exercise 2 - Extracted elements (index 5 to 15):
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [3]:
# Exercise 3
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print("\nExercise 3 - Updated Series:\n", fruit_series)



Exercise 3 - Updated Series:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [4]:
# Exercise 4
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Jane'],
    'age': [25, 30, 35, 40, 22, 28, 33, 45, 26, 38],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}
df = pd.DataFrame(data)
print("\nExercise 4 - DataFrame:\n", df)



Exercise 4 - DataFrame:
       name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    David   40      M
4      Eva   22      F
5    Frank   28      M
6    Grace   33      F
7    Helen   45      F
8      Ian   26      M
9     Jane   38      F


In [5]:
# Exercise 5
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Analyst', 'Manager', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print("\nExercise 5 - DataFrame with Occupation:\n", df)



Exercise 5 - DataFrame with Occupation:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   22      F     Analyst
5    Frank   28      M     Manager
6    Grace   33      F  Programmer
7    Helen   45      F     Manager
8      Ian   26      M     Analyst
9     Jane   38      F  Programmer


In [6]:
# Exercise 6
age_filtered_df = df[df['age'] >= 30]
print("\nExercise 6 - Age >= 30:\n", age_filtered_df)



Exercise 6 - Age >= 30:
       name  age gender  occupation
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
6    Grace   33      F  Programmer
7    Helen   45      F     Manager
9     Jane   38      F  Programmer


In [7]:
# Exercise 7
csv_path = "people_data.csv"
df.to_csv(csv_path, index=False)

# Read CSV
df_read = pd.read_csv(csv_path)
print("\nExercise 7 - Read CSV:\n", df_read)



Exercise 7 - Read CSV:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   22      F     Analyst
5    Frank   28      M     Manager
6    Grace   33      F  Programmer
7    Helen   45      F     Manager
8      Ian   26      M     Analyst
9     Jane   38      F  Programmer
